services:
  - type: web
    name: stilo-api
    env: docker
    region: frankfurt  # or your preferred region
    buildCommand: ""  # Docker will handle the build
    startCommand: ""  # Docker will handle the start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,http://localhost:4200
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: MAX_UPLOAD_SIZE
        value: 10485760
    autoDeploy: true